### ISSUE TITLE
It is worth mentioning...

### ISSUE THREAD

**Issue by alkah3st** [vimeo/player-api#42]
That if you follow these instructions from Vimeo:

http://developer.vimeo.com/player/js-api

You can't use underscores or hyphens in the ID of the embedded Vimeo object/player_id querystring or else froogaloop will never fire the ready event properly. I spent an hour gouging my eyes out over this.

**Comment by mrchimp** [comment]
You shouldn't be using numbers as they are not valid HTML IDs. From [the spec](http://www.w3.org/TR/html401/types.html#type-name):

 > ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".").

**Comment by dbwinger** [comment]
You're right!  Hopefully that wasted time serves me well to never try that again. :)

**Comment by bdougherty** [comment]
We fixed this awhile ago. Any valid id according to the HTML 5 spec should work.
