### ISSUE TITLE
Developer tools chrome net::ERR_CACHE_MISS 

### ISSUE THREAD

**Issue by Szymon-dziewonski** [vimeo/player-api#64]
I did setup my video with api and i get error like that
Failed to load resource: net::ERR_CACHE_MISS 

Then I start wondering if it's something I did wrong, but seems not - original example from here have same error on chrome.

Then I thought maybe its plugin or add-on , but no, opera have same problem and its plain without any plugins 

Any idea's? 
Thank you

**Comment by rkingrum** [comment]
Have you found a fix for this?  I'm getting the same issue.

**Comment by Szymon-dziewonski** [comment]
Hi, it looks like its chrome problem with ad-blocker, anyway I left it alone, cuz it is only on my computer. I checked it on few more computers and its fine
