### ISSUE TITLE
API doesn't provide ability to change quality ?

### ISSUE THREAD

**Issue by magsout** [vimeo/player-api#66]
There is no functions that can choose HD or SD quality video?  
I want to embed your player without toolbar, just add my own button like play, pause etc... But no ability to change HD or SD ? If I embed vidéo I just can provide HD quality ?

**Comment by bdougherty** [comment]
We consider the quality preference to be a viewer setting. Plus and PRO members can set their videos to default to HD in their embed settings. We don't have plans to add any API methods for quality switching.
