### ISSUE TITLE
isReady

### ISSUE THREAD

**Issue by Vozzie** [vimeo/player-api#70]
Hi,

Thanks for the lib, it sure got me going... I just have 2 minor remarks. 1) Shouldn't the API also allow "http" next to "https" . 2) And shouldn't isReady be set after checking the origin instead of before?

Changed 

        if (method == 'ready' && !isReady) {
            isReady = true;
        }

        // Handles messages from the vimeo player only
        if (!(/^https?:\/\/player.vimeo.com/).test(event.origin)) {
            return false;
        }

Into

    if(!/^(?:http|https){1}:\/\/player\.vimeo\.com/g.test(e.origin)) {
        return ralse;
    }
    if (method == 'ready' && !isReady) {
        isReady = true;
    }

**Comment by bdougherty** [comment]
The question mark in the regex operates on the character right before it. If you type into the browser console you will see that they both work.

```
> (/^https?:\/\/player.vimeo.com/).test('https://player.vimeo.com/video/2');
< true
> (/^https?:\/\/player.vimeo.com/).test('http://player.vimeo.com/video/2');
< true
```

You're right that the ready check should be after validating the origin. That is something that works correctly in a new version of the library that's coming soon.

**Comment by Vozzie** [comment]
> ?
SIlly me! Anyway, thx for the work. Made things very clear to me.
