### ISSUE TITLE
Where is the documentation

### ISSUE THREAD

**Issue by gidmeister** [vimeo/player-api#71]
Hi,
I heard that you were considering gathering new information on each event for instance, a play event would also give the exact seek-position where it started.  Function calls were supposed to get an upgrade too.  Has this happened?  Where is the documentation for all of froogaloop?
Thanks,

**Comment by revolunet** [comment]
its here https://developer.vimeo.com/player/js-api but looks like the vimeo web team doesnt have time/ressources to help developers here :/

**Comment by bdougherty** [comment]
We have a new library that we'll be releasing very soon that will have actual documentation. Also, we added that data to most of the events a little while back.
