### ISSUE TITLE
iOS, video won't play if seekTo is called before user initiates playback

### ISSUE THREAD

**Issue by frumbert** [vimeo/player-api#74]
You can't seek to a video that hasn't been initiated by the user, as expected from iOS (safari remote console shows `Error: The viewer must initiate playback first.`).

A fork of the [example](https://developer.vimeo.com/player/js-api) code shows the problem. In a desktop browser, the video precaches and seeks to 35 seconds then starts playing. on iOS, the video enters a loading state and the video is unable to be started (you can toggle pause or drag to a different time - the video never plays)..

http://codepen.io/frumbert/pen/RPZrJz

I'm not seeing any messages in the remote console.

https://player.vimeo.com/playground also demonstrates the problem. Press "seek to" before playing the video.

**Comment by bdougherty** [comment]
Good catch! We will have a fix in the next player release. (I'll update the ticket when it goes out)

**Comment by bdougherty** [comment]
The player has been updated. Tested that codepen and it seems to be working now.
