### ISSUE TITLE
Froogaloop bower support?

### ISSUE THREAD

**Issue by ethanclevenger91** [vimeo/player-api#76]
There's currently a "fork" (https://github.com/austinpray/bower-vimeo-froogaloop) with an attached bower library, but it doesn't seem to be maintained. I issued a PR to update it, but it would be nice if the official repo was attached to a bower library so someone else doesn't have to monitor that sort of thing.

**Comment by bdougherty** [comment]
We will be updating the library with a brand new version soon and it will be available through both npm and bower. Unless there are any really major issues with current version, there won't be any more updates to it.

**Comment by ethanclevenger91** [comment]
Sounds good, thanks!
