### ISSUE TITLE
The viewer must initiate playback first.

### ISSUE THREAD

**Issue by lspoor** [vimeo/player-api#78]
I'm trying to create a simple play button for a vimeo video which has gone fine using the following code below but when clicking the custom play button I receive an error in the console:

'Uncaught Error: The viewer must initiate playback first.'

```javascipt
var player = document.getElementById('video');
	var play = false;
	$f(player).addEvent('ready', ready);

	function addEvent(element, eventName, callback) {
	    if (element.addEventListener) {
	        element.addEventListener(eventName, callback, false)
	    } else {
	        element.attachEvent(eventName, callback, false);
	    }
	}

	function ready(player_id) {
	    var froogaloop = $f(player_id);
	    if (play)
	        froogaloop.api('play');
	}

	$('.play-button').click(function() {
	    $('.hide-these').fadeOut(500, function() {

	        play = true;
	        $f(player).api('play');
	    });
	});
```

I'm also receiving another error when just placing a vimeo video in my code in the console:

Uncaught TypeError: Cannot read property 'getAttribute' of null

**Comment by bdougherty** [comment]
This is a limitation of iOS. The viewer must initiate playback by tapping directly on the player before play and pause can be triggered by the JS API.

**Comment by lspoor** [comment]
I'm not using this on iOS.. this is on Chrome on Mac

**Comment by bdougherty** [comment]
@lspoor do you have device mode turned on in the inspector? There's not much we can do other than to use the User Agent in this case, so if it's set to iPhone then you would see that message.

**Comment by GinoF** [comment]
@lspoor I'm having a similar issue. I've embedded a Vimeo player within a webview in an iOS app and when I try to play the video via javascript I get the same error.

Since the functionality is based off of the User Agent string, I was thinking of modifying it, but that's a last resort. Do you have any suggestions?

Note: I'm able to call the play function on a youtube iframe embed.

**Comment by ixlan** [comment]
The same problem "The viewer must initiate playback first". I can't start the video from a button on Mac google chrome. It works as it should in Firefox and other browsers.

**Comment by Romainpetit** [comment]
You should add this as a comment on the "availability" of the `play()` function for mobile

**Comment by arabold** [comment]
To me this is a illogical limitation of the API. iOS itself prevents auto-play from happening if the developer doesn't explicitly enable it in the web view control. But if he does, then there's no point in further limiting this in the Vimeo API.
