### ISSUE TITLE
ready event not firing on froogaloop object

### ISSUE THREAD

**Issue by crowjonah** [vimeo/player-api#79]
I had some code that follows the documentation very closely (working for well over a year now) just stop working this week. I pass the iframe to `$f()`, use `addEvent` to listen for `ready` and then bind to `pause`, `play`, `finish`, and `playProgress`. Using logs/alerts all over the place, I'm seeing that the player ready event is never bubbling up to the point where I catch it. Please help!

**Comment by ain** [comment]
I can confirm this.

**Comment by mafio** [comment]
Try changing the api id to the id you use on the iframe. Its in the SRC url.

**Comment by piepkrak** [comment]
I can also confirm this.

Also in my case the ready event does get triggered when using https://player.vimeo.com/video/%id. When using HTTP it is not.

**Comment by bdougherty** [comment]
We are working on a new version of the library that will handle stuff like this a lot better. We hope to have it out early next year.

**Comment by Pifalo** [comment]
We had a very similar issue where the ready event never fired. Turns out it was only in Firefox, Chrome worked fine. I came across a blog post which attributed the issue to a Firefox bug where the iframe is not visible and therefor not throwing events (http://www.justinball.com/2014/03/09/firefox-vimeo-and-froogaloop-have-a-little-problem/).

Our solution was basically what the article stated: do not set the iframe source in the markup but set it to a data attribute (data-src); then in our js function where we set up the player we set the iframe src to that data-src value. That resolved the issue for us.

**Comment by Flimm** [comment]
I'm also experiencing this issue in Firefox but not Chrome. The workaround that Pifalo mentioned did not work.

**Comment by nico66** [comment]
Same problem.

**Comment by bdougherty** [comment]
@Flimm sounds like that video was limited to embedding on certain domains. Privacy Badger blocks the referrer, so we can't verify that it's on one of the whitelisted domains. There's really no way for us to detect that. That being said, we are planning to make error pages fire some kind of event so you can detect those.

**Comment by Flimm** [comment]
@bdougherty The videos were on the privacy setting "Hide this video from Vimeo.com", but the embed option was set to "anywhere".

**Comment by JamesGould123** [comment]
I've also been having this problem. The solution for me was to attach the pause, play, and finish events outside of the ready callback, and then in the ready callback remove and re-attach the pause play and finish events. I think the ready event was firing before the JS would run, and this works if the ready event never fires or if it fires too quickly.

**Comment by jmp909** [comment]
I'm finding my ready events aren't firing when i click back on my browser. is there a way to check if the video is ready and call my function directly if it is rather than adding a "ready" event listener?

**Comment by bdougherty** [comment]
I'd encourage everyone to update to the new library, which should resolve the issue https://github.com/vimeo/player.js

**Comment by Flimm** [comment]
Thanks @bdougherty , I'll try migrating to that library. The [migration doc](https://github.com/vimeo/player.js/blob/master/docs/migrate-from-froogaloop.md) looks handy, and the cumbersome `ready` event has been removed, I see!
