### ISSUE TITLE
JS player drops error in IE10 under Win7

### ISSUE THREAD

**Issue by ikondrat** [vimeo/player-api#85]
Steps to reproduce:
1) Open https://developer.vimeo.com/player/js-api
2) Open developer's console and see error - Unable to get property apendChild of undefined

Result:
Black rectangle instead of video player

Reasons as I see IE10 goes in wrong obfuscated function directly to 

> function n(e) {
> var t = arguments.length <= 1 || void 0 === arguments[1] ? {} : arguments[1];
> a(this, n);
> var i = s(this, Object.getPrototypeOf(n).call(this, e, t)), r = e.querySelector("video");
> ...
> i._element.appendChild(r)),
> .....

But actually need to look first at 

> function n(e) {
> var t = arguments.length <= 1 || void 0 === arguments[1] ? {} : arguments[1];
> r(this, n);
> var i = o(this, Object.getPrototypeOf(n).call(this, e, t));
> return i.reset(),
> ...

So he is coming with wrong **this** context without **"_element"** and drops error

**Comment by ccampbell** [comment]
Thanks for the report. We are aware of an issue with IE 10 playback and hope to have a fix soon!

**Comment by ikondrat** [comment]
@ccampbell If you will say where are the sources for this player I will probably can help you with pull request

**Comment by ccampbell** [comment]
@ikondrat thanks, but it's not a bug with the JS library. It's with our player javascript itself (which is not open source).

**Comment by ccampbell** [comment]
@ikondrat this should be resolved now!

**Comment by ikondrat** [comment]
@ccampbell now it's ok, thanks a lot for the quick fix
