### ISSUE TITLE
https forwarded?

### ISSUE THREAD

**Issue by cyphunk** [vimeo/player-api#86]
It appears that your server forwards //a.vimeocdn.com/js/froogaloop2.min.js from HTTP to HTTPS and the browser complains about the certificate.

the error:
`a.vimeocdn.com uses an invalid security certificate. The certificate is only valid for the following names: a248.e.akamai.net, *.akamaihd.net, *.akamaihd-staging.net, *.akamaized.net, *.akamaized-staging.net Error code: SSL_ERROR_BAD_CERT_DOMAIN`

**Comment by bdougherty** [comment]
That url would use https if it's on an https page (http://paulirish.com/2010/the-protocol-relative-url/). Please update to use `https://f.vimeocdn.com/js/froogaloop2.min.js` which will work for both.

**Comment by cyphunk** [comment]
Okay, seriously there is something to review here.

In any browser when going directly to https://a.vimeocdn.com/js/froogaloop2.min.js the certificate is invalid. The error above is what is shown in Firefox and requires creating an acception to pass it. In Chrome the content at least returns one gets a red warning lock icon.

Next, in Firefox when ``<script src="//a.vimeocdn.com/js/froogaloop2.min.js" ></script>`` on an HTTP site the browsers network log window shows this request is changed to HTTPS, and because of the certificate error mentioned above it fails to load. I do not have the EFF's HTTPS everwhere extension installed so I'm not sure why this is happening.

Obviously I have to consider users that use different browsers with different settings. Until the certificate issue is solved I'll host locally.

**Comment by bdougherty** [comment]
Yes, that is why we switched to f.vimeocdn.com when we started supporting https (and the docs were updated with that url).

**Comment by cyphunk** [comment]
Aaah. h, f. My bad. Thanks for clarifying

**Comment by bdougherty** [comment]
FWIW, it was a limitation on the cdn end (secure-a.vimeodcn.com works). We're looking to update a.vimeocdn.com to point to our current cdn, but we have a lot of other higher-priority things at the moment.
