### ISSUE TITLE
Ready event not working locally

### ISSUE THREAD

**Issue by SpabRice** [vimeo/player-api#88]
Hello,

the ready event seems not be fired when working locally.Example
`var iframe = document.getElementById('player1');
var player = $f(iframe);
	
player.addEvent('ready', function() {
	player.api('setVolume', 0);
});`

I never get this to work when opening it locally on my machine.  As soon as I uplaod the file to a server it works fine.  Am I missing something?

**Comment by bdougherty** [comment]
Initially we thought that this was a limitation with the `postMessage` api, but after some investigation, I found a way to make it work. The next version of our player will fix this.

**Comment by bdougherty** [comment]
Update is out.
