### ISSUE TITLE
'ready' event not firing in Chrome when clicking browser 'back' button

### ISSUE THREAD

**Issue by jmp909** [vimeo/player-api#91]
I find my ready events don't fire when I click back in the browser as I mention here
https://github.com/vimeo/player-api/issues/79#issuecomment-229643427

Currently I have multiple videos on a page I'm using an overlay with a custom play button. When the video is "ready" I unhide the element and fade this overlay on. Then when I click the button it fires a ` player.api('play')' event.. none of this works when I click back in my browser. I don't know if it's an issue with the "isReady" variable in froogaloop or the browser cache

This all works fine when going directly to the page, just not when clicking "back".

I'm using  this in my code... so it's not a multiple video issue specfically,  and it's not necessarily a cached video issue as the timestamp I use for the id/player_id changes when I click back.

` <iframe id="video{{timestampedID}}" src="http://player.vimeo.com/video/{{post.postFeatureVideo}}?api=1&player_id=video{{timestampedID}}#timestamp={{timestampedID}}">`

anyone have any suggestions please?

thanks
J

PS i'm trying the amended PR here to resolve a separate issue but neither fix the above issue
https://github.com/vimeo/player-api/pull/83

**Comment by bdougherty** [comment]
Browsers cache pages, so I wouldn't expect the iframe to be reloaded when you hit the back button, which would mean that the ready event wouldn't fire.

This old version is no longer supported, so I'd encourage you to switch to the new library: https://github.com/vimeo/player.js

**Comment by jmp909** [comment]
when i hit back through it is generating a new player_id though, so I imagined it'd be loading in a fresh iframe due to the altered querystring

I'd not seen that new API though, I'll give that a go instead thanks!

j
