### ISSUE TITLE
Deprecation Schedule? 

### ISSUE THREAD

**Issue by dotsam** [vimeo/player-api#93]
I see that the Froogaloop library is no longer supported in favor of the new player.js library. What's the timeline for any possible breaking changes to the player that would cause issues with Froogaloop?

Thanks.

**Comment by bdougherty** [comment]
All of our libraries are just helpers on top of the `postMessage` api. We've tried to design the api to be as forwards-compatible as possible, so there hopefully won't be any breaking changes. For what it's worth, the original version of the api that uses query-string-style messages still works!

If there are ever breaking changes, keep an eye on our [Twitter](https://twitter.com/vimeoapi) and [Blog](http://vimeoapi.tumblr.com) for the details.
