### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by vidiot1969** [vimeo/player-api#98]
Hi,

Using Javascript SDK.  First video is set up with an iframe, subsequent videos are played when loadVideo is called.  However, under lower bandwidth conditions (500kps-1Mbit), the error below occurs and playback/loading does not occur after the call to loadVideo.  Under high bandwidth conditions, the error still occurs but does not seem to affect the loading and play of the video.

Below the error message is my iframe setup.

Please assist!  Thanks.

player.js:22 Uncaught DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
    at t.n.isTimeInBuffer (https://f.vimeocdn.com/p/3.45.3/js/player.js:22:68013)
    at https://f.vimeocdn.com/p/3.45.3/js/player.js:22:78554
    at Array.every (<anonymous>)
    at HTMLVideoElement.n (https://f.vimeocdn.com/p/3.45.3/js/player.js:22:78526)

<iframe
  | id="vid1container"
  | src="https://player.vimeo.com/video/xxxxxxxxx?keyboard=false&controls=false&autoplay=true&quality=auto"
  | frameborder="0"
  | allow="autoplay"
  | width="1920"
  | height="1080"
  | style="float: left; margin-bottom: 2px; visibility: hidden;"
  | ></iframe>

**Comment by fisherinnovation** [comment]
Please move all converstaion to https://github.com/vimeo/player.js moving forward. This repo is archived. 👋
